name: GurkenwasserLobby
version: '${project.version}'
main: wurstwasser.gurkenwasserlobby.startup.GurkenwasserLobby
api-version: '1.20'

commands:
  setlobby:
    description: Sets the lobby spawn point.
  lobby:
    description: Teleports the player to the lobby spawn point.
    aliases: [hub, l]
permissions:
  gurkenwasserlobby.setlobby:
    description: Allows setting the lobby spawn point.
    default: op